version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/parallel_corpus
    depends_on:
      - db
    volumes:
      - ./alembic:/app/alembic
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=parallel_corpus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 