"""create row_words table

Revision ID: 8430960cb8c8
Revises: 
Create Date: 2025-07-10 15:46:39.970635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8430960cb8c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('row_words',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('ID_sen', sa.String(), nullable=True),
    sa.Column('Word', sa.String(), nullable=True),
    sa.Column('Lemma', sa.String(), nullable=True),
    sa.Column('Links', sa.String(), nullable=True),
    sa.Column('Morph', sa.String(), nullable=True),
    sa.Column('POS', sa.String(), nullable=True),
    sa.Column('Phrase', sa.String(), nullable=True),
    sa.Column('Grm', sa.String(), nullable=True),
    sa.Column('NER', sa.String(), nullable=True),
    sa.Column('Semantic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_row_words_ID'), 'row_words', ['ID'], unique=False)
    op.create_index(op.f('ix_row_words_ID_sen'), 'row_words', ['ID_sen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_row_words_ID_sen'), table_name='row_words')
    op.drop_index(op.f('ix_row_words_ID'), table_name='row_words')
    op.drop_table('row_words')
    # ### end Alembic commands ###
