"""create sentence and point tables

Revision ID: 9fbc65e15c2e
Revises: 8430960cb8c8
Create Date: 2025-07-13 08:57:28.141436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbc65e15c2e'
down_revision: Union[str, Sequence[str], None] = '8430960cb8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('startpos', sa.Integer(), nullable=True),
    sa.Column('endpos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence',
    sa.Column('id_sen', sa.String(), nullable=False),
    sa.Column('left', sa.Text(), nullable=True),
    sa.Column('center', sa.Text(), nullable=True),
    sa.Column('right', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_sen')
    )
    op.add_column('row_words', sa.Column('Lang_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('row_words', 'Lang_code')
    op.drop_table('sentence')
    op.drop_table('point')
    # ### end Alembic commands ###
